name: lint

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: abaplint
      uses: abaplint/actions-abaplint@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
